### ISSUE TITLE
Updated for shared library name changes

### ISSUE THREAD

**Issue by dpocock** [xtuple/updater#6]
OpenRPT now builds a shared library called libopenrptcommon

The Updater tries to access it using the name libcommon

Please update the updater code to use the new library names in the same way that the qt-client code has been changed.  Maybe this can be done after the 4.7.0 build is finalized for all platforms.

**Comment by gilmoskowitz** [comment]
fixed by commit 287c140663215a9d00475cefe71638112ad704db
